### PR TITLE
Update github urls.

### LINKED ISSUE #109: Change user agent
- Change from "http://github.com/tntp/surveymonkey" to relocated repo name "http://github.com/mattroumaya/surveymonkey" (like seen [here](https://github.com/mattroumaya/surveymonkey/blob/master/R/request_utils.R#L25)). 
- Also research this more to see if a generic URL can be set as default

### PR DESCRIPTION
**Pull request by nfultz**
Closes #109

### CODE REVIEW

**Comment by nfultz** [comment]
Thanks for maintaining this package, I still use it at work.

**Comment by mattroumaya** [comment]
Thank you so much, @nfultz! This looks great, and if you have any features you'd like to add to this package please feel free to open another PR or file an issue!

**Comment by nfultz** [comment]
Sure, np. Would you mind tagging this PR with the `hacktoberfest-accepted` label to count it towards my stats?

**Comment by mattroumaya** [comment]
@nfultz sure! I added a label - hopefully that's what you mean, but if not just let me know.

**Pull request merged**
